// <auto-generated />
namespace dot_net_Restful.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tenforec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tenforec));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201919289_ten -forec"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
